### DISCUSSION TITLE
Verify multiple times within the same test method?

### DISCUSSION THREAD

**Discussion by glen-84** [VerifyTests/Verify#806] [Q&A] [answered]
I have code like this:

```cs
        await Verify(uploadDetails)
            .ScrubInlineGuids()
            .ScrubMember("Policy");

        var policy = Encoding.UTF8.GetString(
            Convert.FromBase64String((string)uploadDetails.Fields["Policy"]));

        await VerifyJson(policy)
            .UseFileName("test")
            .ScrubInlineGuids();
```

... but Verify only seems to work for the first call. Is this not possible?

I would have expected this to work, even without the `UseFileName`, by automatically appending an index to the file name.

I'm aware of #772, but even if it _was_ possible (I'm trying to target a specific dictionary key), I think that it makes more sense for it to be written to a separate file, otherwise it looks like this property is actually an object in the first snapshot.

**Comment by SimonCropp** [comment]
try this 

```
var policy = Encoding.UTF8.GetString(
    Convert.FromBase64String((string)uploadDetails.Fields["Policy"]));

await VerifyJson(new {uploadDetails,policy})
    .ScrubInlineGuids();
```

**Reply by glen-84** [reply]
It doesn't work with `VerifyJson`, only `Verify`.

> Argument 1: cannot convert from '<anonymous type: Api.Modules.Common.Domain.Model.Files.UploadDetails uploadDetails, string policy>' to 'string?' [Api.UnitTests]

This still combines the result into one file, and the policy obviously isn't processed as JSON.

As mentioned, if they're combined then it's not really a WYSIWYG situation, the actual data doesn't have this separated `policy` property. That's why I'd prefer it to be written to a separate file.

```yml
{
  uploadDetails: {
    Url: https://.../test,
    Fields: {
      bucket: test,
      Policy: {Scrubbed} # Processed separately as JSON.
    }
  }
}
```

```yml
{
  expiration: DateTimeOffset_1,
  conditions: [...]
}
```
